codegouvfr/react-dsfr

package.json, src/Badge.tsx, stories/Badge.stories.tsx
[See DSFR documentation](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/badge)
=> feat: add badge component

src/Accordion.tsx
If an application does not have the `@gouvfr/dsfr` module installed, the following error is expected: 
```
./node_modules/@codegouvfr/react-dsfr/Accordion.js
Module not found: Can't resolve '@gouvfr/dsfr/component/accordion/accordion.css' in 'path\to\application\node_modules\@codegouvfr\react-dsfr'
```
Given that the css required is also in the `@codegouvfr/react-dsfr` module, we can locate this css locally in the module and prevent dependency errors. 
Signed-off-by: Matt Clark  <87824367+isMattCoding@users.noreply.github.com>
=> Change the import location for accordion.css

package.json, src/Quote.tsx, stories/Quote.stories.tsx
Ajout composant Quote
~~Dans [la doc DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/citation) ca parle de "couleurs d'accent" et de différentes tailles possibles, je n'ai pas compris de quoi il s'agit~~
```ts
export type QuoteProps = {
className?: string;
text: string;
author?: string;
source?: ReactNode;
sourceUrl?: string;
image?: string;
size?: "md" | "lg" | "xl";
};
```
=> feat: add Quote component

COMPONENTS.md, package.json, src/ToggleSwitch.tsx, stories/ToggleSwitch.stories.tsx, stories/ToggleSwitchGroup.stories.tsx
j'ai mis `ToggleSwitch` et `ToggleSwitchGroup` dans le même fichier, a voir s'il vaut mieux séparer
Comment on doit gérer le controlled/uncontrolled ? je vais prendre exemple sur Accordion
=> feat: add ToggleSwitch

src/Input.tsx
Using this component, I thought some `<label>` related improvments could be useful:
- a `hideLabel` prop: not documented on DSFR docs, but we could allow users to provide a valid label but hide it (using sr-only to make it still readable by screen readers).
- removed aria-labelled attribute: as long as the label prop is mandatory and linked to the related input with htmlFor, I don't see why we should keep it.
- I added the support of the type file input (https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/ajout-de-fichier), wrapping it with a `fr-upload-group` : I was about creating a new component (to follow DSFR naming and docs), but it appears that Input and File are just the same, only the wrapper class is changing. Maybe we should create a File component that just …
=> Input adjustements

src/Button.tsx
I came across an issue: I did want to use this component as a submit button form a form element, but its typing doesn't allow the usage as a <button> without a onClick prop.
I'm not sure passing onClick as optional is the best option, but even as a `<button type="button">`, I'm not sure we should constrain the user to pass a onClick prop.
Alternatively, we could pass onClick as optional if the button `type` attribute is `submit` or `reset`.
=> Button onClick can be optional

css-in-js.md
Signed-off-by: Nicolas KOKLA <1872767+nkokla@users.noreply.github.com>
=> doc: typo on `useIsDark` in css-in-js page

README.md
By default, pnpm is not implementing pre and post scripts so we have to enable them with the `.npmrc` file.
This PR implements documentation for installing the _react-dsfr_ library on projects using pnpm as a package manager.
=> docs: pnpm support

src/Select.tsx, stories/Select.stories.tsx
While checking [this issue](https://github.com/codegouvfr/react-dsfr/issues/62) I noticed that the Select component could be more convenient to use. Based on what [we did on Immersion Facilitée](https://github.com/betagouv/immersion-facile/blob/dev/libs/react-design-system/src/immersionFacile/components/select/Select.tsx) and works a lot like component like `react-select`.
Basically, instead of using `<option>` as children, options are passed as as props (SelectOption<CustomValue>[]), and it can take a `placeholder` prop.
I find it more convenient IMO.
=> Feature / updated Select component

src/Modal.tsx
Description: This pull request addresses the issue of duplicated IDs by modifying the code to use the modal ID for creating the H1 ID. This change ensures that the H1 ID remains unique, even when multiple modals are present on the same page.
=> Fix duplicated IDs issue while using multiple modals in a single page

README.fr.md
correction de typos + il manque un ou plusieurs mots ligne 50.
=> feat: correct typos

.storybook/main.js, package.json, src/blocks/PasswordInput.tsx, src/scripts/list-exports.ts, stories/blocks/PasswordInput.stories.tsx, stories/blocks/sectionName.ts, yarn.lock
Implémentation of the password functional block : https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles-et-blocs-fonctionnels/demande-de-mot-de-passe
Not sure about the typing of the props. I based them from the InputProps but not sure that was a good idea. Let met know if you think it's better to have an independent typing, I will do the change.
The pre-commit hook   change the export on the package.json and not sure how it's works. I let the package.json on the pull request but let me know if I have to do something. It doesn't add the PasswordInput in the list but I think it's because I put it under a "blocks" folder. Same, let me know if I have to  move the component or change something
=> feat: Add password functional block

package.json, src/scripts/list-exports.ts
Just a little issue on the path to blocks folder path on the exports.
=> fix: fix exports of blocks components

src/Footer.tsx
When screen readers render these li, all of the links tend to render in one block. the `&nbsp;` helps keep them separated and shouldn't affect the style.
=> Add non breaking space before the end of li

stories/Modal.stories.tsx
Fix typo on `Modal`component code description.
=> Fix `Modal.stories.tsx` code documentation

src/Footer.tsx
Forgot the React keys.
It may be interesting to add https://github.com/jsx-eslint/eslint-plugin-react to avoid that kind of mistakes.
=> fix(footer): add missing key in footer link list

src/Tile.tsx
The proposed change for the Tile component involves adding a feature to specify the width and height of the optional image.  I added imageWidth & imageHeight optionnal properties to follow the imageUrl & imageAlt pattern.
I'll make another suggestion : introduce an imageProps object, similar to the existing linkProps object, which would provide greater flexibility and control over the image properties. 
I am open to discussing this further.
=> fix: add imageWidth & imageHeight properties on Tile

src/ToggleSwitch.tsx
Add a name attribute to ToggleSwitch input.
Permit to handle the input like a normal html input when a form is submitted.
=> feat(ToggleSwitch): Add name attribute to ToggleSwitch

package.json, src/scripts/list-exports.ts
Hi !
I would like to import `setLink()` or `getLink()` from the link module to have access to the Link implementation but this module is not exported.
Is this ok ?
=> Export link module

src/Modal.tsx
Hi there ! 
Default button type is "submit" in most browsers, this has fired "submit" events if the modal is embedded in a form for example.
Setting the type to "button" seems more in line with the intent in this case.
What do you think ?
=> Set button types as "button" for modal open and close buttons

src/Modal.tsx
Hi again :)
This one is more tricky.
During compilation of a next app with server component, sometime the createModal() call happens in 2 different contexts.
The result is a server rendering with `${uncapitalize(name)}-modal-0` and a client bundle with  `${uncapitalize(name)}-modal-1`
This has caused us a bug during hydration (aria-controls of the hidden modal control button are different), but also the button does not work in production at all since the aria-controls prop have a different id than the modal.
I am ok with the developers having the responsibility of putting unique modal names (as when using basic dsfr js)
But I am aware that this PR is a BC break for this component, what do you think ?
=> Remove counter for generating modal ids

src/Accordion.tsx
I'm trying to implement the Accordion component to make a multi-step form.
I noticed that right now, the `button` to toggle the Accordion has its default type (submit): when used in a form, it submits the form. I know this is a edge case, but I think it's less restrictive to use a `type="button"`.
=> Feature / Adjustments on Accordion

src/Card.tsx
The DSFR's cards footer are div, not paragraph.
Now ButtonsGroup can be added as footer without any semantic html error like "ul should be inside of p"
=> fix(card): change card footer card to div to be semantic

src/SelectNext.tsx, stories/SelectNext.stories.tsx
I just removed the hidden attribut in the placeholder because in chrome the first option was looking like it's selected whilee it's not.
previous behavior:
actual behavior:
=> remove hidden attribute on placeholder plus fix typo in story

src/Alert.tsx
Remove empty title tags in small size components when the title is not provided.
=> fix: optional title for alert components

src/SelectNext.tsx
Hello team,
thanks for this amazing work.
Just a PR to fix a wrong default spelling in SelectNext component.
Regards,
=> fix: SelectNext - wrong FR spelling

src/Input.tsx
Sets the `type` property to `undefined`  when the Input is a `<textarea>`.
`type` is left unchanged for `<input>` elements.
See issue #159
=> fix(Input): no type on textarea

src/Card.tsx, stories/Card.stories.tsx
Choose heading level in card title (h2, h3 ...)
=> feat: Choose Hx level for Card title ref #160

README.md, components.md, css-in-js.md, i18n.md, icons.md, mui.md, publishing-a-npm-modules-that-depends-on-react-dsfr.md, routing.md
- Fixed some typos
- Fixed broken link to Color helper
- Added a tip to restart local server to see newly added icons: when I started using react-dsfr, it took me some time to understand that, and it was asked a few weeks ago in the DSFR Slack, so it might be useful for other people :)
=> chore(docs): add tips to see new icons && typos

src/Upload.tsx, stories/Upload.stories.tsx
- feat: Keep default label for backward compatibility
- doc: Update Upload story
=> feat(upload): add label props #167

src/Footer.tsx
I've added title in all the links with target="_blank"
=> fix: Add title for footer links that open in a new tab #153

src/SelectNext.tsx, test/types/Select.tsx
Hi,
We've encountered a typing issue using SelectNext, turns out `target` and `currentTarget` on `onChange` event had the wrong type :
I added type tests to check this. I think there's no consequences for the runtime. I also changed the selectedOptions prop, to fit our value typing needs.
=> fix wrong type on target / currentTarget on SelectNext

src/Input.tsx
When an Input is `type="date"`, DSFR already change the native icon with the ri-calendar icon in Webkit based browser.
In Firefox, since there is no `-moz-` support from DSFR, the native is displayed, therefore adding another one is wrong:
This PR remove the add of the date icon from the `<Input />` component
=> fix: remove duplicate icon when input type date

src/Button.tsx
For some use case we need to add "value" to button. We could use nativeButtonProps but it would be more natural to accept it as a base props in my opinion. The code already supports it but it's not typed
=> Add "value" for button props

src/Header/Header.tsx
Mise en place d'une extension de classe sur le container
=> Mise en place d'une extension de classe sur le container:  Header.tsx

src/Card.tsx, stories/Card.stories.tsx
refs #164 
! BREAKING CHANGE !
* only one badge in the image area (`badges` becomes `badge`)
* update storybook: add more examples and update props list
=> feat(Card)!: update component to match dsfr guidelines (refs #164)

src/Badge.tsx, stories/Badge.stories.tsx, stories/Header.stories.tsx
- Badge can be a span or a p (default p). Same logic as the Summary component.
- Update Badge default story
- Create Header story with beta badge
Note: it works locally on storybook, but I'm not sure how to test on vite or next app for example. I launched the command `yarn start-vite` but it didn't create a local dev server, so I don't know what I'm supposed to do.
=> feat(Badge): element can be a span (ref #200)

src/Display/Display.tsx
As described in the doc and for accessibility purposes, the aria-hidden=true attribute was missing on the svgs in the display component
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/parametre-d-affichage/
=> fix:add-aria-hidden-to-display-svg

src/Footer.tsx
Always open partners logo links in new tabs.
See issue #205 .
Among the possible fixes, this is the most simple and this doesn't introduce any breaking change.
Making opening in new tabs the default and only behavior makes sense. Other external links in the Footer (legifrance.gouv.fr, gouvernement.fr...)  have the same behavior.
=> Open partners logo link in new tabs

src/Follow.tsx, src/Input.tsx, src/blocks/PasswordInput.tsx, stories/ButtonsGroup.stories.tsx, stories/Follow.stories.tsx, stories/Input.stories.tsx, test/integration/next-appdir/app/Follow.tsx, test/integration/next-appdir/app/layout.tsx
Closes #219 
- add `Follow` component and allow customisation of some sort
- handle usage of custom `form` component (e.g. ReactHookForm)
- add `addon` property to `Input` component (but prevent usage in `PasswordInput` component)
=> feat: Follow component

src/Card.tsx, stories/Card.stories.tsx
- add a way to use custom image component to `Card` instead of "normal" `<img>` tag (e.g. SVG, `next/Image`). The user should add `fr-img-responsive` to its component.
- enhance `Card` props
- add tier and half ratio
=> feat(card): add tier and half ratio, add image component

src/Footer.tsx
add a `classes.operatorLogo` for the footer and use `classes.logo` for the main logo.
the goal is to be able to apply a custom class to the main logo
This will be a breaking change for those using `classes.logo` for the `operatorLogo`
Not sure if this was intended or not
=> fix(footer): add missing classes.operatorLogo

src/consentManagement/Placeholder.tsx, stories/ConsentManagement.stories.tsx, test/types/consentManagement.tsx
I added the consentManager's Placeholder component based on the example given on the stories.
While adding the consent manager on our project, the CI failed on accessbility tests (aXe). I took the liberty to add `titleAs` so we have not to stick to arbitrary H levels on the DSFR examples (which are, depending on the context, accessibility issues):
- replaced consentManager title by **span**, which won't break title hierarchy
- Placeholder title with titleAs prop (which default to h4 - same behavior as the dsfr demo)
- replaced consentManager modal wrapper tag by dialog (instead of div, to resolve missing landmarks issues)
Still discussing on it on Mattermost: https://mattermost.incubateur.net/betagouv/threads/jnzhstsadbdjib9ithqhotte7h
=> Feature / add consentManager Placeholder component

src/Header/Header.tsx, stories/Header.stories.tsx
Add a way to "split" the enlarge link when an operator logo is given with additional link props
=> feat: header operator link

src/Footer.tsx, stories/Footer.stories.tsx
- change "href" for "linkProps" for partners logos (mark "href" as deprecated to avoid BC)
- if no link is provided, only the image is displayed
=> feat: footer partners link

src/CallOut.tsx
Following [DSFR Doc](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/mise-en-avant) looks like we should be able to custom the CallOut title tag.
thanks
=> fix(CallOut): allow custom title tag

src/Footer.tsx
En France, on met un espace avant et après les ":"
=> Add space in wording

stories/Range.stories.tsx, stories/SegmentedControl.stories.tsx
Some url in StoryBook were incorrect
=> fix: storybook urls were incorrect

src/Tabs.tsx
When tabs appear inside forms, the buttons are considered "submit" buttons.
=> fix(tabs): set buttons as buttons

stories/Accordion.stories.tsx
J'ai remarqué qu'il manquait la propriété `titleAs` dans la doc pour les accordéons.
=> doc(accordion): add missing titleAs props to the documentation

src/Pagination.tsx
ATM when on the first or last page of the pagination component, a `Link` component is generated with no `href` attribute for the `first / last page` and `previous / next page` elements of the pagination.
The issue seem to have been running for almost a year now https://github.com/codegouvfr/react-dsfr/issues/170
Issue : Since NextJS can't handle `Link` without an `href` attribute, the whole page crashes if we're on the first or last page of the pagination component.
Steps to reproduce : Clone react-dsfr, use a Pagination component in `test/integration/next-appdir/ui/ClientComponent.tsx`.
Set `defaultPage` attribue to either 1 or the same as `count` count attribute, and `count` > 1.
Run and try to access the page.
example : 
```
<Pagination
getPageLinkProps={(page) => ({ href: …
```
=> fix(Pagination): Allow usage of Pagination component with Next.js

src/Input.tsx, src/Range.tsx, src/SegmentedControl.tsx, src/Select.tsx, src/SelectNext.tsx, src/ToggleSwitch.tsx, src/Upload.tsx, src/blocks/PasswordInput.tsx, src/shared/Fieldset.tsx
The props `label` and `hintText` are ReactNodes. They can therefore be null, undefined, or an empty string (""). In these cases, the rendered HTML will be an empty `<label>` tag. This PR fixes this issue.
There is a side effect: if the provided `label` or `hintText` is the boolean `false`, it will not be displayed. I don't think this is problematic; it will simply require casting the boolean to a string.
=> fix: do not display empty `<label></label>`

src/Card.tsx
J'ai dû recréer une PR pour voir un historique OK suite à la PR https://github.com/codegouvfr/react-dsfr/pull/285.
Comme conseillé dans la PR, j'introduis `nativeImgProps` qui est transmis à l'image des Card. (et donc le fameux `loading="lazy"` qui m'intéresse)
=> Ajoute nativeImgProps pour les Card

src/consentManagement/createConsentManagement.ts, stories/ConsentManagement.stories.tsx, test/integration/vite/src/consentManagement.tsx
Hi! Here's my attempt to customise the localStorage key for analytics consents #302.
This PR :
- adds a `localStorageKeyPrefix` parameter to the `createConsentManagement` function
- keeps the original `localStorageKeyPrefix`, renamed to `defaultLocalStorageKeyPrefix`, as the default prefix
- adds `consentLocalStorageKey` (the calculated key) to the returned object of the `createConsentManagement` function, so that it can be used by later by the user
- updated the story
=> feat: customize localStorage key for analytics consents #302

src/Input.tsx, src/Select.tsx
Wrapped the error message within a parent with attribute ~~aria-live="assertive"~~ aria-live="polite" so that it gets announced by the screen reader
Update 1: Added similar wrapper to Select component
- https://github.com/codegouvfr/react-dsfr/issues/311
=> [Accessibility] Input/Select - wrapped error message within live region

src/Modal/Modal.tsx
In the Modal component, the icon is missing an attribute "aria-hidden" for the screen readers as it is purely decorative
=> [Accessibility] Modal component - aria-hidden missing from the span representing an icon

.storybook/preview.js, src/ProConnectButton.tsx, src/assets/proconnect-btn.css, stories/FranceConnectButton.stories.tsx
ProConnect will replace AgentConnect and MonComptePro in the next few days.
Find out more at https://www.proconnect.gouv.fr/.
This PR also introduce 3 fixes:
- conflict between ProConnect and FranceConnect css rules
- wrong FranceConnect documentation link
- wrong "what is service" link on ProConnect component
=> fix(ProConnectButton): ProConnect is out!

src/Pagination.tsx
I was running Axe with Playwright on https://github.com/gip-inclusion/immersion-facile and the validation didn't pass because of missing aria-disabled attribute on the Pagination next page / last page items.
=> fixed missing aria-disabled label on pagination

src/SideMenu.tsx
Fix the issue #319
Not sure if i did all the requirements in order to contribute to the repo, feel free to ask me further dev / informations.
=> fix: be able to use sidemenu with multiple 3 levels submenus

src/Summary.tsx, stories/Summary.stories.tsx
Évolution suite à l'issue #330
Il y a un comportement d'espacement entre les éléments profonds et le reste du sommaire qui est problématique, mais il est causé par le DSFR en lui-même. J'ai donc créé un [ticket de suggestion](https://systeme-de-design.featureupvote.com/suggestions/590786/conserver-un-espace-constant-entre-les-elements-dans-le-composant-sommaire)
=> feat(summary): add subitems

src/Header/Header.tsx, src/Input.tsx, src/Modal/Modal.tsx
Correction d'erreurs sémantiques remonté par l'outil d'analyse https://validator.w3.org/ sur notre site :
https://validator.w3.org/nu/?doc=https%3A%2F%2Fcode-du-travail-numerique-preprod.ovh.fabrique.social.gouv.fr%2Fmentions-legales
Il y a 3 erreurs corrigées :
Le role dialog sur une dialog n'est pas requis car implicite avec la balise dialog. Pour moi, ce devrait être un warning mais ça remonte en erreur.
Ici on utilise deux fois le même id. Je pense que c'est une erreur de copier/coller car le second id est sur un bouton pour fermer la recherche. Je l'ai donc renommé pour que ça corresponde à son role.
On ajoute aria-describedby sur l'input même si l'on a pas de message descriptif.
=> fix: W3C html semantic errors

src/Tooltip.tsx
Hello,
The default type on a button is "submit". This cause problems when the tooltip is used in a form since clicking on the tooltip will cause a submit of the form.
Just setting the type on the button to type="button" will fix this.
=> fix: tooltip button type shouldn't be submit

src/Footer.tsx
Official DSFR documentation switched partners heading level from h4 to h2 to prevent gaps in heading levels.
This heading level doesn't have to be customized.
For additional context, I raised this issue on slack last year : https://gouvfr.slack.com/archives/C012RFZPTRN/p1691743144369259
HeadingMaps capture showing the issue with h4 on a random page :
=> fix(Footer): change partners heading level

src/Tile.tsx, stories/Tile.stories.tsx
⚠️ This would be a breaking change as the option `imageSvg` will not default to `true` anymore.
The reason for that change is that, as it stands, the `Tile` component is not usable with standard SVG or other image format unless the property `imageSvg={false}` is set
=> fix(Tile): do not default to SVGImage to true otherwise it doesn't work with standard svg

src/Footer.tsx, src/SkipLinks.tsx
Hi! In the Footer component, there are a few hard-coded links but their anchor tags that don't have an id. So I added a simple code to automatically add an id to them.
And the SkipLinks component accepts a list of links but the current typed list doesn't accept an id for each of the links. So I changed the type to specify the id of each link.
=> feat: add id on anchor tags for analytics

package.json, src/Input.tsx, src/blocks/PasswordInput.tsx, stories/Input.stories.tsx
- add "fr-input-wrap--action"
- enable a way to inject classes to wrapper
https://storybook.systeme-de-design.gouv.fr/?path=/docs/input--docs&globals=viewport:lg#action%20story
=> feat(input): add action and enable wrap class access

src/MainNavigation/MegaMenu.tsx, stories/MainNavigation.stories.tsx
On ajoute la possibilté d’ajouter une catégorie aux megamenu sans lien comme décrit dans cette [issue](https://github.com/codegouvfr/react-dsfr/issues/352).
=> Ajout categoryMainText à Category

src/Header/Header.tsx
We need an ID on the label for accessibility purposes. We have a custom input with autocomplete and need to link the suggestion list to the label through an ID.
=> feat: add an id to the label

src/Input.tsx
Sometimes, we need to add properties to the label for accessibility purposes. In our case, we need to add an ID to meet autocomplete accessibility requirements.
=> feat: add a native label props on Input

stories/Select.stories.tsx
Petit fix qui corrige les liens vers la doc DSFR et le code du composant dans la documentation du composant Select
=> Fix DSFR docs & source links on Select page

src/Select.tsx, src/shared/Fieldset.tsx
Bonjour,
En rajoutant la possibilité de mettre des bulles infos, j'ai induit une incohérence graphique sur le repository.
Le but étant que lorsqu'on passe le state `info`, qu'il y ait uniquement le message en bas qui s'affiche en bleu et non tout l'input, comme ce que je vous partage ci-dessous.
Merci ☺️
=> fix(info): remove blue color for all the question

stories/charts/BarChart.stories.tsx, stories/charts/BarLineChart.stories.tsx, stories/charts/GaugeChart.stories.tsx, stories/charts/LineChart.stories.tsx, stories/charts/MultiLineChart.stories.tsx, stories/charts/PieChart.stories.tsx, stories/charts/RadarChart.stories.tsx, stories/charts/ScatterChart.stories.tsx, stories/getStory.tsx
Cette Pull Request ajoute une partie du chemin manquante aux stories qui concernent les composants Charts.
Ces composants sont présents dans le répertoire /Charts mais ce répertoire est manquant dans le chemin d'import de la documentation.
Un nouveau paramètre a été créé pour identifier les composants Charts et ajouter le dossier dans le chemin d'import
Fixes #378 
Ajout d'un paramètre isChartComponent dans la fonction getStory avec la valeur false par défaut et d'une règle qui permet d'ajouter le dossier Chart au chemin d'import si le composant est un Chart :
``` const pathComponent = isChartComponent ? `Chart/${componentName}` : componentName; ```
Ce paramètre est ajouté avec la valeur true dans toutes les stories des composants Chart
=> Add folder Chart in path when the component is a chart

src/Chart/PieChart.tsx, stories/charts/PieChart.stories.tsx
Cette Pull Request corrige le problème de type du name du composant PieChart. Le graphique camembert affiche plusieurs séries suivant leurs proportions et il faut pouvoir nommer ces séries.
Même si dans la documentation il est bien indiqué que c'est un Array of name, comme le PieChartBaseProps est basé sur le ChartProps et que ce dernier a comme type name?: string, il n'est pas possible de mettre un tableau et donc de nommer les différentes séries
Fixes #370 
Le type ```ChartProps = {
x: any[];
y: number[];
name?: string;
color?: ChartColor;
};``` est utilisé par plusieurs composants donc il n'a pas été modifié, nous avons plutôt ajouter le type dans ```
PieChartBaseProps = {
fill?: boolean;
name?: string[];
} & ChartProps;```
=> Add type array of string for name of PieChart

src/Chart/BarLineChart.tsx, src/Chart/chartWrapper.tsx, stories/charts/BarLineChart.stories.tsx
Cette Pull Request ajoute la possibilité de mettre un nom au Bar dans le composant BarLineChart.
Elle corrige également un problème de stringify non nécessaire lorsque que un paramètre était de type `string.` 
Fixes https://github.com/codegouvfr/react-dsfr/issues/371
=> Fix: impossible to set a name for the bar in barline chart

src/Chart/PieChart.tsx
Cette Pull Request est la suite de la #377. La propriété color a été ajoutée dans le PieChartBaseProps mais en la rendant obligatoire. 
Nous proposons d'ajouter la possibilité qu'elle soit undefined et ainsi de prendre les couleurs par défaut.
J'en profite pour vous indiquer qu'une nouvelle version 2.0.0 de DSFR-Charts est sortie hier :
https://github.com/GouvernementFR/dsfr-chart/releases/tag/v2.0.0
Cette version est active et est amenée à évoluer au cours de l'année. Je vais voir si la migration se fait simplement et je vous tiendrai au courant
Fixes #384 
Comme pour les autres propriétés, un ? a été ajouté pour que la propriété color puisse être undefined :
```color?: ChartColor[];```
=> Charts - PieCharts : Add undefined to color prop

src/Tile.tsx
=> Fix usage of div in Tile

src/SideMenu.tsx, stories/SideMenu.stories.tsx
Issue found with an accessibility tool while auditing my site :-)
Thanks for react-dsfr!
=> fix(SideMenu): Don't include aria-labelledby when no title exists

src/assets/dsfr_plus_icons.css, src/assets/dsfr_plus_icons.scss
This PR just wraps the included dsfr css in a dsfr layer.  This allows codebases that are using the nextjs pages dir to better prioritize the dsfr css with respect to their own or third party libraries.
For example, at Réfugiés.info, we have a legacy codebase with several different frameworks historically including for example some bootstrap.  We use a @layers directive to help prioritize these different and sometimes conflicting css files.
https://github.com/refugies-info/karfur/blob/89b999a95d7d547a3f0749da41c7e17a0d7379f7/apps/client/src/css/index.css#L1
Since react-dsfr imports dsfr.min.css in the Next Pages Router integration:
https://github.com/codegouvfr/react-dsfr/blob/16f7f11ecc370b330016044ccdb3664b25c9ad5a/src/next-pagesdir.tsx#L24
We currently resort to patching the …
=> feat: :lipstick: Wrap dsfr css imports in a dsfr layer

src/SelectNext.tsx
Voici une proposition de Pull Request pour venir corriger l'issue : [#402](https://github.com/codegouvfr/react-dsfr/issues/402).
Le travail a été réalisé par [MBrandone](https://github.com/MBrandone) pour le [Select](https://github.com/codegouvfr/react-dsfr/blob/main/src/Select.tsx) dans la PR suivante : [#403](https://github.com/codegouvfr/react-dsfr/pull/403) mais le problème est toujours présent sur le [SelectNext](https://github.com/codegouvfr/react-dsfr/blob/main/src/SelectNext.tsx).
La correction consiste donc à ne pas avoir l'attribut aria-describedby sur l'élément select quand il possède un state à "default" car aucun élément avec cet ID dans le DOM ne lui est associé.
=> fix(SelectNext): No generation of aria-describedby referencing a non-existant id in the case of a default state (#402)

src/assets/dsfr_plus_icons.css
I would like to revert this PR because my tests have not been conclusive.  Indeed, it appears that [support of native CSS features](https://github.com/webpack/webpack/issues/14893) such as
`@import url("...") layer(layerName)`
is only slated for webpack 6 which hasn't been released yet.  I tried enabling these new features in the latest webpack version 5.99.8  using the `experimental.css: true` webpack config setting but this caused major breakage of our UI.
Reverts codegouvfr/react-dsfr#400
=> Revert "feat: :lipstick: Wrap dsfr css imports in a dsfr layer"

src/consentManagement/ConsentBannerAndConsentManagement/ConsentBannerAndConsentManagement.tsx, src/consentManagement/ConsentBannerAndConsentManagement/ConsentManagement.tsx, src/consentManagement/createConsentManagement.ts, src/consentManagement/types.ts, stories/ConsentManagement.stories.tsx
Right now, ConsentManager only allows sub-finalities to have a title. It's a ReactNode, but it's rendered as a child of a <legend> element, which should only be used for the title part of the finality.
This PR allows sub-finalities to also have a separate description, which is more aligned with the DSFR documentation.
=> Fix - Handle subfinality description in ConsentManager

src/Alert.tsx
=> feat(Alert): add custom role, status or alert
