- package.json
- src/Breadcrumb.tsx
- stories/Breadcrumb.stories.tsx
Premier essai avec le composant Breadcrumb
> feat: add Breadcrumb component

- package.json
- src/Stepper.tsx
- stories/Stepper.stories.tsx
add Stepper component for https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/indicateur-d-etape/
```
export type StepperProps = {
className?: string;
currentStep: number;
steps: number;
title: string;
nextTitle?: string;
};
```
> feat: add Stepper component

- src/Breadcrumb.tsx
- stories/Breadcrumb.stories.tsx
small improvements
Also removed the `trimText` function so the user is responsible of text overflows if any
> fix(Breadcrumb): classes+i18n

- src/Card.tsx
> fix(Card): more TS

- stories/Footer.stories.tsx
Following up this thread
https://twitter.com/GarroneJoseph/status/1606024725121052673
Example content copied from https://entreprendre.service-public.fr/
> fix: avoid using lorem ipsum in footer

- src/Header/Header.tsx
To provide more control on styles on the operator logo.
> Feat / add classes.operator on Header

- COMPONENTS.md
- package.json
- src/Tile.tsx
- stories/Tile.stories.tsx
- stories/getStory.tsx
> feat: add Tile component

- COMPONENTS.md
- package.json
- src/Pagination.tsx
- stories/Pagination.stories.tsx
A discuter :
- API
- gestion des `linkProps`
> feat: add Pagination component

- README.md
Signed-off-by: lonelil <51315646+lonelil@users.noreply.github.com>
> fix: "Looking to contribute?" not a title in English README

- css-in-js.md
Signed-off-by: Julia Dirand <julia.dirand@gmail.com>
> Fix typo in css-in-js.md

- .eslintrc.js
- README.fr.md
- README.md
- package.json
- src/Select.tsx
- stories/ColorHelper/Search.tsx
- stories/Select.stories.tsx
- test/integration/vite/src/Home.tsx
- test/types/Select.tsx
Fixing Select component as discussed : https://github.com/codegouvfr/react-dsfr/issues/75
> Feature / select fix

- src/Tabs.tsx
See : https://github.com/codegouvfr/react-dsfr/issues/172
> fix: tabs issue after PR 152

- README.fr.md
- README.md
- publiccode.yml
L'ancien lien renvois vers une page non trouvée
> Mise a jour du lien Etalab

- README.md
Hello !
Diagoriente vient de déployer son nouveau site web développé avec react-dsfr ! La lib est vraiment intuitive et le DS est vraiment chouette, bien joué à tous ceux qui y ont contribué, j'espère avoir l'occasion d'y contribuer prochainement également.
Petite PR pour nous ajouter à la liste des utilisateurs 😃
> docs: add Diagoriente to use cases

- src/Stepper.tsx
cf https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/indicateur-d-etapes/
I don't know if it's a mistake or a dsfr change 🤷‍♂️
> fix(Stepper): title where not a the right place

- src/Tile.tsx
Oups, j'avais laissé un nom de variable temporaire dans la PR #277
> fix: typo in Tile.tsx #277

- README.md
- assets.md
- colors.md
- components.md
- icons.md
- add doc about `--silent` 
- correct a few typos & phrasing
> docs: few suggestions to the gitbook doc

- package.json
- src/next-appdir/DsfrHead.tsx
- src/next-pagesdir.tsx
https://github.com/codegouvfr/react-dsfr/issues/303#issuecomment-2352597216
> No script when only light

- src/Tile.tsx
> fix(Tile): show download icon on Tile With Download Link

- icons.md
> docs: Update icons.md

- src/Notice.tsx
- stories/Notice.stories.tsx
> feat(notice): add severity, description and link

- src/SelectNext.tsx
- stories/SelectNext.stories.tsx
> fix(SelectNext): Accept `defaultValue`

- src/SearchBar/SearchBar.tsx
- stories/SearchBar.stories.tsx
PR for adding a `defaultValue` props to the `SearchBar` component solving issue #380.
> feat(SearchBar): add defaultValue
